name: actionlint

on:
  pull_request:
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: reviewdog/action-actionlint@49cb3ce06e5d81452e14b38ad34e4b12a8acfe2b # v1.73.3
        with:
          reporter: github-pr-review
          fail_on_error: true
