name: actionlint

on:
  pull_request:
    paths:
      - ".github/actions/**"
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: reviewdog/action-actionlint@8b682e1e7e512151d73a6b9449cbff173846226e # v1.74.0
        with:
          reporter: github-pr-review
          fail_on_error: true
