name: blog post workflow

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.6.3
        with:
          max_post_count: "3"
          feed_list: "https://9renpoto.dev/rss.xml"
