name: blog post workflow

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
      - uses: gautamkrishnar/blog-post-workflow@1.9.3
        with:
          feed_list: "https://9renpoto.win/rss.xml"
