name: blog post workflow

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@1.8.8
        with:
          feed_list: "https://9renpoto.win/rss.xml,https://sizu.me/9renpoto/rss"
