name: Update README

on:
  schedule:
    - cron: '0 0-12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@v0.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - uses: gautamkrishnar/blog-post-workflow@1.4.9
        with:
          max_post_count: "3"
          feed_list: "https://9renpoto.dev/rss.xml"

      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@V1.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_PROJECTS: "False"
