name: Update README

on:
  schedule:
    - cron: '0 0-12/4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@V3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_PROJECTS: "False"
