name: wakatime

on:
  schedule:
    - cron: '0 0-12/4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: name: Waka - Readme
        uses: athul/waka-readme@v0.2.3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
