name: wakatime

on:
  schedule:
    - cron: "0 0-12/4 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5
      - name: Waka - Readme
        uses: athul/waka-readme@v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
